version: 2
models:
  - name: stg_posts
    description: Cleaned staging model for posts
    columns:
      - name: post_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]
